_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 100
max_shown_results: 20
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
allow_single_deselect: true
disabled_themes:
  claro: '0'
  olivero: '0'
chosen_include: 0
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
