_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: fad9fcef-464d-4971-9e31-42ce4cf88c8a
name: 'My Drupal 9 Site'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /transactions
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
